#!/bin/bash

usage() {
  echo "Usage $0 [OPTIONS]"
  echo "Monkemacs friendly neighborhood helper."
  echo " -h, --help"
  echo " -i, --install Installs the monkemacs environment."
  echo " -v, --verbose Make the helper yap a lot."
}

has_argument() {
    [[ ("$1" == *=* && -n ${1#*=}) || ( ! -z "$2" && "$2" != -*)  ]];
}

extract_argument() {
  echo "${2:-${1#*=}}"
}

handle_options() {
  while [ $# -gt 0 ]; do
    case $1 in
    -h | --help)
      usage
      exit 0
      ;;
    -v | --verbose)
      verbose_mode=true
      ;;
    -i | --install)
      install=true
      ;;
    esac
    shift
  done
}

handle_options "$@"

if [ "$verbose_mode" = true ]; then
  echo "Verbose mode enabled."
fi

if [ "$install" = true ]; then
  mv init.el ../init.el
  echo "init.el was copied into the root dir :)"
fi
