#!/bin/bash

usage() {
  echo "Usage $0 [OPTIONS]"
  echo "Monkemacs friendly neighborhood helper."
  echo " -h, --help"
  echo " -i, --install Installs the monkemacs environment."
  echo " -v, --verbose Make the helper yap a lot."
}

has_argument() {
  [[ ("$1" == *=* && -n ${1#*=}) || (! -z "$2" && "$2" != -*) ]]
}

extract_argument() {
  echo "${2:-${1#*=}}"
}

handle_options() {
  while [ $# -gt 0 ]; do
    case $1 in
    -h | --help)
      usage
      exit 0
      ;;
    -v | --verbose)
      verbose_mode=true
      ;;
    -i | --install)
      install=true
      ;;
    esac
    shift
  done
}

handle_options "$@"

if [ "$verbose_mode" = true ]; then
  echo "Verbose mode enabled."
fi

MONKEY_PATH="$(dirname -- "${BASH_SOURCE[0]}")"
FINAL_PATH="${MONKEY_PATH%/[^/]*}"
MONKEY_PATH="$(cd -- "$MONKEY_PATH" && pwd)"
FINAL_PATH="$(cd -- "$FINAL_PATH" && pwd)"

if [[ -z "$MONKEY_PATH" ]]; then
  exit 1
fi

if [ "$install" = true ]; then
  export MONKEMACS_CONFIG_PATH="$HOME/.config/emacs/"
  mv $MONKEY_PATH"/init.el" $MONKEMACS_CONFIG_PATH
  echo "init.el was copied into the root dir :)"
fi
